/*
 * Visa Account Updater
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AccountUpdatesResponse
 */
class AccountUpdatesResponseTest {
    private final AccountUpdatesResponse model = new AccountUpdatesResponse();

    /**
     * Model tests for AccountUpdatesResponse
     */
    @Test
    void testAccountUpdatesResponse() {
        // TODO: test AccountUpdatesResponse
    }

    /**
     * Test the property 'responseCode'
     */
    @Test
    void responseCodeTest() {
        // TODO: test responseCode
    }

    /**
     * Test the property 'oldExpirationDate'
     */
    @Test
    void oldExpirationDateTest() {
        // TODO: test oldExpirationDate
    }

    /**
     * Test the property 'oldCardholderAccountNumber'
     */
    @Test
    void oldCardholderAccountNumberTest() {
        // TODO: test oldCardholderAccountNumber
    }

    /**
     * Test the property 'acquirerOrMerchantProprietaryInfo'
     */
    @Test
    void acquirerOrMerchantProprietaryInfoTest() {
        // TODO: test acquirerOrMerchantProprietaryInfo
    }

}
