/*
 * Visa Account Updater
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.RejectMerchantSearch;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Merchant
 */
class MerchantTest {
    private final Merchant model = new Merchant();

    /**
     * Model tests for Merchant
     */
    @Test
    void testMerchant() {
        // TODO: test Merchant
    }

    /**
     * Test the property 'city'
     */
    @Test
    void cityTest() {
        // TODO: test city
    }

    /**
     * Test the property 'state'
     */
    @Test
    void stateTest() {
        // TODO: test state
    }

    /**
     * Test the property 'reject'
     */
    @Test
    void rejectTest() {
        // TODO: test reject
    }

    /**
     * Test the property 'merchantId'
     */
    @Test
    void merchantIdTest() {
        // TODO: test merchantId
    }

    /**
     * Test the property 'postalCode'
     */
    @Test
    void postalCodeTest() {
        // TODO: test postalCode
    }

    /**
     * Test the property 'contactName'
     */
    @Test
    void contactNameTest() {
        // TODO: test contactName
    }

    /**
     * Test the property 'countryCode'
     */
    @Test
    void countryCodeTest() {
        // TODO: test countryCode
    }

    /**
     * Test the property 'contactEmail'
     */
    @Test
    void contactEmailTest() {
        // TODO: test contactEmail
    }

    /**
     * Test the property 'contactPhone'
     */
    @Test
    void contactPhoneTest() {
        // TODO: test contactPhone
    }

    /**
     * Test the property 'merchantName'
     */
    @Test
    void merchantNameTest() {
        // TODO: test merchantName
    }

    /**
     * Test the property 'parentCompany'
     */
    @Test
    void parentCompanyTest() {
        // TODO: test parentCompany
    }

    /**
     * Test the property 'cardAcceptorId'
     */
    @Test
    void cardAcceptorIdTest() {
        // TODO: test cardAcceptorId
    }

    /**
     * Test the property 'merchantStatus'
     */
    @Test
    void merchantStatusTest() {
        // TODO: test merchantStatus
    }

    /**
     * Test the property 'streetAddress1'
     */
    @Test
    void streetAddress1Test() {
        // TODO: test streetAddress1
    }

    /**
     * Test the property 'streetAddress2'
     */
    @Test
    void streetAddress2Test() {
        // TODO: test streetAddress2
    }

    /**
     * Test the property 'internetAddress'
     */
    @Test
    void internetAddressTest() {
        // TODO: test internetAddress
    }

    /**
     * Test the property 'merchantDescriptor'
     */
    @Test
    void merchantDescriptorTest() {
        // TODO: test merchantDescriptor
    }

    /**
     * Test the property 'merchantCategoryCode'
     */
    @Test
    void merchantCategoryCodeTest() {
        // TODO: test merchantCategoryCode
    }

    /**
     * Test the property 'merchantLineBusiness'
     */
    @Test
    void merchantLineBusinessTest() {
        // TODO: test merchantLineBusiness
    }

    /**
     * Test the property 'merchantAcquiringIdentifiers'
     */
    @Test
    void merchantAcquiringIdentifiersTest() {
        // TODO: test merchantAcquiringIdentifiers
    }

}
