/*
 * Visa Account Updater
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RejectedRequestResponse
 */
class RejectedRequestResponseTest {
    private final RejectedRequestResponse model = new RejectedRequestResponse();

    /**
     * Model tests for RejectedRequestResponse
     */
    @Test
    void testRejectedRequestResponse() {
        // TODO: test RejectedRequestResponse
    }

    /**
     * Test the property 'merchantId'
     */
    @Test
    void merchantIdTest() {
        // TODO: test merchantId
    }

    /**
     * Test the property 'rejectReason'
     */
    @Test
    void rejectReasonTest() {
        // TODO: test rejectReason
    }

    /**
     * Test the property 'subMerchantName'
     */
    @Test
    void subMerchantNameTest() {
        // TODO: test subMerchantName
    }

    /**
     * Test the property 'rejectReasonCode'
     */
    @Test
    void rejectReasonCodeTest() {
        // TODO: test rejectReasonCode
    }

    /**
     * Test the property 'acquirerSegmentId'
     */
    @Test
    void acquirerSegmentIdTest() {
        // TODO: test acquirerSegmentId
    }

}
