/*
 * Visa Account Updater
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.LocalDate;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RejectedStopAdviceResponse
 */
class RejectedStopAdviceResponseTest {
    private final RejectedStopAdviceResponse model = new RejectedStopAdviceResponse();

    /**
     * Model tests for RejectedStopAdviceResponse
     */
    @Test
    void testRejectedStopAdviceResponse() {
        // TODO: test RejectedStopAdviceResponse
    }

    /**
     * Test the property 'startDate'
     */
    @Test
    void startDateTest() {
        // TODO: test startDate
    }

    /**
     * Test the property 'rejectCode'
     */
    @Test
    void rejectCodeTest() {
        // TODO: test rejectCode
    }

    /**
     * Test the property 'merchantName'
     */
    @Test
    void merchantNameTest() {
        // TODO: test merchantName
    }

    /**
     * Test the property 'rejectMessage'
     */
    @Test
    void rejectMessageTest() {
        // TODO: test rejectMessage
    }

    /**
     * Test the property 'cardAcceptorId'
     */
    @Test
    void cardAcceptorIdTest() {
        // TODO: test cardAcceptorId
    }

    /**
     * Test the property 'cardholderAccountNumber'
     */
    @Test
    void cardholderAccountNumberTest() {
        // TODO: test cardholderAccountNumber
    }

}
