/*
 * Visa Account Updater
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.RejectedInquiryResponse;
import org.openapitools.client.model.SuccessfulInquiryResponse;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Response
 */
class ResponseTest {
    private final Response model = new Response();

    /**
     * Model tests for Response
     */
    @Test
    void testResponse() {
        // TODO: test Response
    }

    /**
     * Test the property 'rejects'
     */
    @Test
    void rejectsTest() {
        // TODO: test rejects
    }

    /**
     * Test the property 'responses'
     */
    @Test
    void responsesTest() {
        // TODO: test responses
    }

    /**
     * Test the property 'merchantId'
     */
    @Test
    void merchantIdTest() {
        // TODO: test merchantId
    }

    /**
     * Test the property 'subMerchantName'
     */
    @Test
    void subMerchantNameTest() {
        // TODO: test subMerchantName
    }

    /**
     * Test the property 'acquirerSegmentId'
     */
    @Test
    void acquirerSegmentIdTest() {
        // TODO: test acquirerSegmentId
    }

    /**
     * Test the property 'acquirerOrMerchantProprietaryInfo'
     */
    @Test
    void acquirerOrMerchantProprietaryInfoTest() {
        // TODO: test acquirerOrMerchantProprietaryInfo
    }

}
