/*
 * Visa Account Updater
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.StopAdvice;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for StopAdviceRequest
 */
class StopAdviceRequestTest {
    private final StopAdviceRequest model = new StopAdviceRequest();

    /**
     * Model tests for StopAdviceRequest
     */
    @Test
    void testStopAdviceRequest() {
        // TODO: test StopAdviceRequest
    }

    /**
     * Test the property 'stopadvices'
     */
    @Test
    void stopadvicesTest() {
        // TODO: test stopadvices
    }

    /**
     * Test the property 'issuerSegmentId'
     */
    @Test
    void issuerSegmentIdTest() {
        // TODO: test issuerSegmentId
    }

}
