/*
 * Visa Account Updater
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.openapitools.client.model.RejectedSubscription;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SubscriptionEnquiryPanStatus
 */
class SubscriptionEnquiryPanStatusTest {
    private final SubscriptionEnquiryPanStatus model = new SubscriptionEnquiryPanStatus();

    /**
     * Model tests for SubscriptionEnquiryPanStatus
     */
    @Test
    void testSubscriptionEnquiryPanStatus() {
        // TODO: test SubscriptionEnquiryPanStatus
    }

    /**
     * Test the property 'reject'
     */
    @Test
    void rejectTest() {
        // TODO: test reject
    }

    /**
     * Test the property 'subscribedStatus'
     */
    @Test
    void subscribedStatusTest() {
        // TODO: test subscribedStatus
    }

    /**
     * Test the property 'cardholderAccountNumber'
     */
    @Test
    void cardholderAccountNumberTest() {
        // TODO: test cardholderAccountNumber
    }

    /**
     * Test the property 'acquirerOrMerchantProprietaryInfo'
     */
    @Test
    void acquirerOrMerchantProprietaryInfoTest() {
        // TODO: test acquirerOrMerchantProprietaryInfo
    }

}
