/*
 * Visa Account Updater
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.openapitools.client.model.RejectedSubscriptionResponse;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SubscriptionResponseAttributes
 */
class SubscriptionResponseAttributesTest {
    private final SubscriptionResponseAttributes model = new SubscriptionResponseAttributes();

    /**
     * Model tests for SubscriptionResponseAttributes
     */
    @Test
    void testSubscriptionResponseAttributes() {
        // TODO: test SubscriptionResponseAttributes
    }

    /**
     * Test the property 'reject'
     */
    @Test
    void rejectTest() {
        // TODO: test reject
    }

    /**
     * Test the property 'expirationDate'
     */
    @Test
    void expirationDateTest() {
        // TODO: test expirationDate
    }

    /**
     * Test the property 'subscribedStatus'
     */
    @Test
    void subscribedStatusTest() {
        // TODO: test subscribedStatus
    }

    /**
     * Test the property 'newExpirationDate'
     */
    @Test
    void newExpirationDateTest() {
        // TODO: test newExpirationDate
    }

    /**
     * Test the property 'serviceIdentifier'
     */
    @Test
    void serviceIdentifierTest() {
        // TODO: test serviceIdentifier
    }

    /**
     * Test the property 'cardholderAccountNumber'
     */
    @Test
    void cardholderAccountNumberTest() {
        // TODO: test cardholderAccountNumber
    }

    /**
     * Test the property 'newCardholderAccountNumber'
     */
    @Test
    void newCardholderAccountNumberTest() {
        // TODO: test newCardholderAccountNumber
    }

    /**
     * Test the property 'acquirerOrMerchantProprietaryInfo'
     */
    @Test
    void acquirerOrMerchantProprietaryInfoTest() {
        // TODO: test acquirerOrMerchantProprietaryInfo
    }

}
