/*
 * Visa Account Updater
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.InquirySubscriptionAttributes;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SubscriptionInquiryRequest
 */
class SubscriptionInquiryRequestTest {
    private final SubscriptionInquiryRequest model = new SubscriptionInquiryRequest();

    /**
     * Model tests for SubscriptionInquiryRequest
     */
    @Test
    void testSubscriptionInquiryRequest() {
        // TODO: test SubscriptionInquiryRequest
    }

    /**
     * Test the property 'merchantId'
     */
    @Test
    void merchantIdTest() {
        // TODO: test merchantId
    }

    /**
     * Test the property 'subscriptions'
     */
    @Test
    void subscriptionsTest() {
        // TODO: test subscriptions
    }

    /**
     * Test the property 'subMerchantName'
     */
    @Test
    void subMerchantNameTest() {
        // TODO: test subMerchantName
    }

    /**
     * Test the property 'acquirerSegmentId'
     */
    @Test
    void acquirerSegmentIdTest() {
        // TODO: test acquirerSegmentId
    }

}
