/*
 * Visa Account Updater
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SuccessfulInquiryResponse
 */
class SuccessfulInquiryResponseTest {
    private final SuccessfulInquiryResponse model = new SuccessfulInquiryResponse();

    /**
     * Model tests for SuccessfulInquiryResponse
     */
    @Test
    void testSuccessfulInquiryResponse() {
        // TODO: test SuccessfulInquiryResponse
    }

    /**
     * Test the property 'newExpirationDate'
     */
    @Test
    void newExpirationDateTest() {
        // TODO: test newExpirationDate
    }

    /**
     * Test the property 'oldExpirationDate'
     */
    @Test
    void oldExpirationDateTest() {
        // TODO: test oldExpirationDate
    }

    /**
     * Test the property 'serviceIdentifier'
     */
    @Test
    void serviceIdentifierTest() {
        // TODO: test serviceIdentifier
    }

    /**
     * Test the property 'previouslySentFlag'
     */
    @Test
    void previouslySentFlagTest() {
        // TODO: test previouslySentFlag
    }

    /**
     * Test the property 'newCardholderAccountNumber'
     */
    @Test
    void newCardholderAccountNumberTest() {
        // TODO: test newCardholderAccountNumber
    }

    /**
     * Test the property 'oldCardholderAccountNumber'
     */
    @Test
    void oldCardholderAccountNumberTest() {
        // TODO: test oldCardholderAccountNumber
    }

}
