/*
 * Visa Account Updater
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * EncryptedPayload
 */
@JsonPropertyOrder({
  EncryptedPayload.JSON_PROPERTY_ENC_DATA
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-29T11:09:21.433785600+01:00[Africa/Casablanca]", comments = "Generator version: 7.12.0")
public class EncryptedPayload {
  public static final String JSON_PROPERTY_ENC_DATA = "encData";
  @jakarta.annotation.Nullable
  private String encData;

  public EncryptedPayload() {
  }

  public EncryptedPayload encData(@jakarta.annotation.Nullable String encData) {
    
    this.encData = encData;
    return this;
  }

  /**
   * Get encData
   * @return encData
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ENC_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEncData() {
    return encData;
  }


  @JsonProperty(JSON_PROPERTY_ENC_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEncData(@jakarta.annotation.Nullable String encData) {
    this.encData = encData;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EncryptedPayload encryptedPayload = (EncryptedPayload) o;
    return Objects.equals(this.encData, encryptedPayload.encData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(encData);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EncryptedPayload {\n");
    sb.append("    encData: ").append(toIndentedString(encData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

