/*
 * Visa Account Updater
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * [Reject Request]
 */
@JsonPropertyOrder({
  GenericErrorMessage.JSON_PROPERTY_REJECT_REASON,
  GenericErrorMessage.JSON_PROPERTY_REJECT_REASON_CODE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-29T11:09:21.433785600+01:00[Africa/Casablanca]", comments = "Generator version: 7.12.0")
public class GenericErrorMessage {
  public static final String JSON_PROPERTY_REJECT_REASON = "rejectReason";
  @jakarta.annotation.Nullable
  private String rejectReason;

  public static final String JSON_PROPERTY_REJECT_REASON_CODE = "rejectReasonCode";
  @jakarta.annotation.Nullable
  private String rejectReasonCode;

  public GenericErrorMessage() {
  }

  public GenericErrorMessage rejectReason(@jakarta.annotation.Nullable String rejectReason) {
    
    this.rejectReason = rejectReason;
    return this;
  }

  /**
   * This fields contains following reject reasons * Internal Server Error, please try again after sometime 
   * @return rejectReason
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REJECT_REASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRejectReason() {
    return rejectReason;
  }


  @JsonProperty(JSON_PROPERTY_REJECT_REASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRejectReason(@jakarta.annotation.Nullable String rejectReason) {
    this.rejectReason = rejectReason;
  }

  public GenericErrorMessage rejectReasonCode(@jakarta.annotation.Nullable String rejectReasonCode) {
    
    this.rejectReasonCode = rejectReasonCode;
    return this;
  }

  /**
   * This Fields contains following Reject reason codes: * E 
   * @return rejectReasonCode
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REJECT_REASON_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRejectReasonCode() {
    return rejectReasonCode;
  }


  @JsonProperty(JSON_PROPERTY_REJECT_REASON_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRejectReasonCode(@jakarta.annotation.Nullable String rejectReasonCode) {
    this.rejectReasonCode = rejectReasonCode;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GenericErrorMessage genericErrorMessage = (GenericErrorMessage) o;
    return Objects.equals(this.rejectReason, genericErrorMessage.rejectReason) &&
        Objects.equals(this.rejectReasonCode, genericErrorMessage.rejectReasonCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(rejectReason, rejectReasonCode);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GenericErrorMessage {\n");
    sb.append("    rejectReason: ").append(toIndentedString(rejectReason)).append("\n");
    sb.append("    rejectReasonCode: ").append(toIndentedString(rejectReasonCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

