/*
 * Visa Account Updater
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.openapitools.client.model.RejectMerchant;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * [Merchant Response]
 */
@JsonPropertyOrder({
  MerchantResponse.JSON_PROPERTY_REJECT,
  MerchantResponse.JSON_PROPERTY_MERCHANT_ID,
  MerchantResponse.JSON_PROPERTY_ENROLL_STATUS,
  MerchantResponse.JSON_PROPERTY_MERCHANT_NAME
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-29T11:09:21.433785600+01:00[Africa/Casablanca]", comments = "Generator version: 7.12.0")
public class MerchantResponse {
  public static final String JSON_PROPERTY_REJECT = "reject";
  @jakarta.annotation.Nullable
  private RejectMerchant reject;

  public static final String JSON_PROPERTY_MERCHANT_ID = "merchantId";
  @jakarta.annotation.Nullable
  private String merchantId;

  public static final String JSON_PROPERTY_ENROLL_STATUS = "enrollStatus";
  @jakarta.annotation.Nonnull
  private String enrollStatus;

  public static final String JSON_PROPERTY_MERCHANT_NAME = "merchantName";
  @jakarta.annotation.Nullable
  private String merchantName;

  public MerchantResponse() {
  }

  public MerchantResponse reject(@jakarta.annotation.Nullable RejectMerchant reject) {
    
    this.reject = reject;
    return this;
  }

  /**
   * Get reject
   * @return reject
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REJECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RejectMerchant getReject() {
    return reject;
  }


  @JsonProperty(JSON_PROPERTY_REJECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReject(@jakarta.annotation.Nullable RejectMerchant reject) {
    this.reject = reject;
  }

  public MerchantResponse merchantId(@jakarta.annotation.Nullable String merchantId) {
    
    this.merchantId = merchantId;
    return this;
  }

  /**
   * [Acquirer assigns the merchant ID. This field must contain a valid VAU Merchant ID.]
   * @return merchantId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MERCHANT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMerchantId() {
    return merchantId;
  }


  @JsonProperty(JSON_PROPERTY_MERCHANT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMerchantId(@jakarta.annotation.Nullable String merchantId) {
    this.merchantId = merchantId;
  }

  public MerchantResponse enrollStatus(@jakarta.annotation.Nonnull String enrollStatus) {
    
    this.enrollStatus = enrollStatus;
    return this;
  }

  /**
   * [Merchant enrollment status, This field contains one of the following status: * Success — Merchant is enrolled successfully * In-Progress — Merchant enrollment is in progress * Reject — Merchant is rejected, reject code and reject message will be returned] 
   * @return enrollStatus
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ENROLL_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getEnrollStatus() {
    return enrollStatus;
  }


  @JsonProperty(JSON_PROPERTY_ENROLL_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEnrollStatus(@jakarta.annotation.Nonnull String enrollStatus) {
    this.enrollStatus = enrollStatus;
  }

  public MerchantResponse merchantName(@jakarta.annotation.Nullable String merchantName) {
    
    this.merchantName = merchantName;
    return this;
  }

  /**
   * [Name of Merchant]
   * @return merchantName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MERCHANT_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMerchantName() {
    return merchantName;
  }


  @JsonProperty(JSON_PROPERTY_MERCHANT_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMerchantName(@jakarta.annotation.Nullable String merchantName) {
    this.merchantName = merchantName;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MerchantResponse merchantResponse = (MerchantResponse) o;
    return Objects.equals(this.reject, merchantResponse.reject) &&
        Objects.equals(this.merchantId, merchantResponse.merchantId) &&
        Objects.equals(this.enrollStatus, merchantResponse.enrollStatus) &&
        Objects.equals(this.merchantName, merchantResponse.merchantName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(reject, merchantId, enrollStatus, merchantName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MerchantResponse {\n");
    sb.append("    reject: ").append(toIndentedString(reject)).append("\n");
    sb.append("    merchantId: ").append(toIndentedString(merchantId)).append("\n");
    sb.append("    enrollStatus: ").append(toIndentedString(enrollStatus)).append("\n");
    sb.append("    merchantName: ").append(toIndentedString(merchantName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

