/*
 * Visa Account Updater
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * [List of merchant enrolment]
 */
@JsonPropertyOrder({
  MerchantRequest.JSON_PROPERTY_CITY,
  MerchantRequest.JSON_PROPERTY_STATE,
  MerchantRequest.JSON_PROPERTY_MERCHANT_ID,
  MerchantRequest.JSON_PROPERTY_POSTAL_CODE,
  MerchantRequest.JSON_PROPERTY_CONTACT_NAME,
  MerchantRequest.JSON_PROPERTY_COUNTRY_CODE,
  MerchantRequest.JSON_PROPERTY_CONTACT_EMAIL,
  MerchantRequest.JSON_PROPERTY_CONTACT_PHONE,
  MerchantRequest.JSON_PROPERTY_MERCHANT_NAME,
  MerchantRequest.JSON_PROPERTY_PARENT_COMPANY,
  MerchantRequest.JSON_PROPERTY_CARD_ACCEPTOR_ID,
  MerchantRequest.JSON_PROPERTY_STREET_ADDRESS1,
  MerchantRequest.JSON_PROPERTY_STREET_ADDRESS2,
  MerchantRequest.JSON_PROPERTY_INTERNET_ADDRESS,
  MerchantRequest.JSON_PROPERTY_MERCHANT_DESCRIPTOR,
  MerchantRequest.JSON_PROPERTY_MERCHANT_CATEGORY_CODE,
  MerchantRequest.JSON_PROPERTY_MERCHANT_LINE_BUSINESS,
  MerchantRequest.JSON_PROPERTY_MERCHANT_ACQUIRING_IDENTIFIERS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-29T11:09:21.433785600+01:00[Africa/Casablanca]", comments = "Generator version: 7.12.0")
public class MerchantRequest {
  public static final String JSON_PROPERTY_CITY = "city";
  @jakarta.annotation.Nullable
  private String city;

  public static final String JSON_PROPERTY_STATE = "state";
  @jakarta.annotation.Nullable
  private String state;

  public static final String JSON_PROPERTY_MERCHANT_ID = "merchantId";
  @jakarta.annotation.Nonnull
  private String merchantId;

  public static final String JSON_PROPERTY_POSTAL_CODE = "postalCode";
  @jakarta.annotation.Nullable
  private String postalCode;

  public static final String JSON_PROPERTY_CONTACT_NAME = "contactName";
  @jakarta.annotation.Nullable
  private String contactName;

  public static final String JSON_PROPERTY_COUNTRY_CODE = "countryCode";
  @jakarta.annotation.Nonnull
  private String countryCode;

  public static final String JSON_PROPERTY_CONTACT_EMAIL = "contactEmail";
  @jakarta.annotation.Nullable
  private String contactEmail;

  public static final String JSON_PROPERTY_CONTACT_PHONE = "contactPhone";
  @jakarta.annotation.Nullable
  private String contactPhone;

  public static final String JSON_PROPERTY_MERCHANT_NAME = "merchantName";
  @jakarta.annotation.Nonnull
  private String merchantName;

  public static final String JSON_PROPERTY_PARENT_COMPANY = "parentCompany";
  @jakarta.annotation.Nullable
  private String parentCompany;

  public static final String JSON_PROPERTY_CARD_ACCEPTOR_ID = "cardAcceptorId";
  @jakarta.annotation.Nonnull
  private String cardAcceptorId;

  public static final String JSON_PROPERTY_STREET_ADDRESS1 = "streetAddress1";
  @jakarta.annotation.Nullable
  private String streetAddress1;

  public static final String JSON_PROPERTY_STREET_ADDRESS2 = "streetAddress2";
  @jakarta.annotation.Nullable
  private String streetAddress2;

  public static final String JSON_PROPERTY_INTERNET_ADDRESS = "internetAddress";
  @jakarta.annotation.Nullable
  private String internetAddress;

  public static final String JSON_PROPERTY_MERCHANT_DESCRIPTOR = "merchantDescriptor";
  @jakarta.annotation.Nullable
  private String merchantDescriptor;

  public static final String JSON_PROPERTY_MERCHANT_CATEGORY_CODE = "merchantCategoryCode";
  @jakarta.annotation.Nonnull
  private String merchantCategoryCode;

  public static final String JSON_PROPERTY_MERCHANT_LINE_BUSINESS = "merchantLineBusiness";
  @jakarta.annotation.Nullable
  private String merchantLineBusiness;

  public static final String JSON_PROPERTY_MERCHANT_ACQUIRING_IDENTIFIERS = "merchantAcquiringIdentifiers";
  @jakarta.annotation.Nonnull
  private List<String> merchantAcquiringIdentifiers = new ArrayList<>();

  public MerchantRequest() {
  }

  public MerchantRequest city(@jakarta.annotation.Nullable String city) {
    
    this.city = city;
    return this;
  }

  /**
   * [Merchant city name]
   * @return city
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCity() {
    return city;
  }


  @JsonProperty(JSON_PROPERTY_CITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCity(@jakarta.annotation.Nullable String city) {
    this.city = city;
  }

  public MerchantRequest state(@jakarta.annotation.Nullable String state) {
    
    this.state = state;
    return this;
  }

  /**
   * [Merchant state name]
   * @return state
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getState() {
    return state;
  }


  @JsonProperty(JSON_PROPERTY_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setState(@jakarta.annotation.Nullable String state) {
    this.state = state;
  }

  public MerchantRequest merchantId(@jakarta.annotation.Nonnull String merchantId) {
    
    this.merchantId = merchantId;
    return this;
  }

  /**
   * [Acquirer assigns the merchant ID. This field must contain a valid VAU Merchant ID.]
   * @return merchantId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MERCHANT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getMerchantId() {
    return merchantId;
  }


  @JsonProperty(JSON_PROPERTY_MERCHANT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMerchantId(@jakarta.annotation.Nonnull String merchantId) {
    this.merchantId = merchantId;
  }

  public MerchantRequest postalCode(@jakarta.annotation.Nullable String postalCode) {
    
    this.postalCode = postalCode;
    return this;
  }

  /**
   * [Merchant postal code]
   * @return postalCode
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_POSTAL_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPostalCode() {
    return postalCode;
  }


  @JsonProperty(JSON_PROPERTY_POSTAL_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPostalCode(@jakarta.annotation.Nullable String postalCode) {
    this.postalCode = postalCode;
  }

  public MerchantRequest contactName(@jakarta.annotation.Nullable String contactName) {
    
    this.contactName = contactName;
    return this;
  }

  /**
   * [Merchant contact name]
   * @return contactName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONTACT_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getContactName() {
    return contactName;
  }


  @JsonProperty(JSON_PROPERTY_CONTACT_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContactName(@jakarta.annotation.Nullable String contactName) {
    this.contactName = contactName;
  }

  public MerchantRequest countryCode(@jakarta.annotation.Nonnull String countryCode) {
    
    this.countryCode = countryCode;
    return this;
  }

  /**
   * [Merchant ISO country code]
   * @return countryCode
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_COUNTRY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCountryCode() {
    return countryCode;
  }


  @JsonProperty(JSON_PROPERTY_COUNTRY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCountryCode(@jakarta.annotation.Nonnull String countryCode) {
    this.countryCode = countryCode;
  }

  public MerchantRequest contactEmail(@jakarta.annotation.Nullable String contactEmail) {
    
    this.contactEmail = contactEmail;
    return this;
  }

  /**
   * [Merchant contact email]
   * @return contactEmail
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONTACT_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getContactEmail() {
    return contactEmail;
  }


  @JsonProperty(JSON_PROPERTY_CONTACT_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContactEmail(@jakarta.annotation.Nullable String contactEmail) {
    this.contactEmail = contactEmail;
  }

  public MerchantRequest contactPhone(@jakarta.annotation.Nullable String contactPhone) {
    
    this.contactPhone = contactPhone;
    return this;
  }

  /**
   * [Contact phone number of the merchant]
   * @return contactPhone
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONTACT_PHONE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getContactPhone() {
    return contactPhone;
  }


  @JsonProperty(JSON_PROPERTY_CONTACT_PHONE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContactPhone(@jakarta.annotation.Nullable String contactPhone) {
    this.contactPhone = contactPhone;
  }

  public MerchantRequest merchantName(@jakarta.annotation.Nonnull String merchantName) {
    
    this.merchantName = merchantName;
    return this;
  }

  /**
   * [Name of Merchant]
   * @return merchantName
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MERCHANT_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getMerchantName() {
    return merchantName;
  }


  @JsonProperty(JSON_PROPERTY_MERCHANT_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMerchantName(@jakarta.annotation.Nonnull String merchantName) {
    this.merchantName = merchantName;
  }

  public MerchantRequest parentCompany(@jakarta.annotation.Nullable String parentCompany) {
    
    this.parentCompany = parentCompany;
    return this;
  }

  /**
   * [Parent company name of  the merchants]
   * @return parentCompany
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PARENT_COMPANY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getParentCompany() {
    return parentCompany;
  }


  @JsonProperty(JSON_PROPERTY_PARENT_COMPANY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setParentCompany(@jakarta.annotation.Nullable String parentCompany) {
    this.parentCompany = parentCompany;
  }

  public MerchantRequest cardAcceptorId(@jakarta.annotation.Nonnull String cardAcceptorId) {
    
    this.cardAcceptorId = cardAcceptorId;
    return this;
  }

  /**
   * [Merchant card acceptor id]
   * @return cardAcceptorId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CARD_ACCEPTOR_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCardAcceptorId() {
    return cardAcceptorId;
  }


  @JsonProperty(JSON_PROPERTY_CARD_ACCEPTOR_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCardAcceptorId(@jakarta.annotation.Nonnull String cardAcceptorId) {
    this.cardAcceptorId = cardAcceptorId;
  }

  public MerchantRequest streetAddress1(@jakarta.annotation.Nullable String streetAddress1) {
    
    this.streetAddress1 = streetAddress1;
    return this;
  }

  /**
   * [Address1 for the merchant]
   * @return streetAddress1
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STREET_ADDRESS1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStreetAddress1() {
    return streetAddress1;
  }


  @JsonProperty(JSON_PROPERTY_STREET_ADDRESS1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStreetAddress1(@jakarta.annotation.Nullable String streetAddress1) {
    this.streetAddress1 = streetAddress1;
  }

  public MerchantRequest streetAddress2(@jakarta.annotation.Nullable String streetAddress2) {
    
    this.streetAddress2 = streetAddress2;
    return this;
  }

  /**
   * [Address2 for the merchant]
   * @return streetAddress2
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STREET_ADDRESS2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStreetAddress2() {
    return streetAddress2;
  }


  @JsonProperty(JSON_PROPERTY_STREET_ADDRESS2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStreetAddress2(@jakarta.annotation.Nullable String streetAddress2) {
    this.streetAddress2 = streetAddress2;
  }

  public MerchantRequest internetAddress(@jakarta.annotation.Nullable String internetAddress) {
    
    this.internetAddress = internetAddress;
    return this;
  }

  /**
   * [Internet address for the merchant]
   * @return internetAddress
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INTERNET_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getInternetAddress() {
    return internetAddress;
  }


  @JsonProperty(JSON_PROPERTY_INTERNET_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInternetAddress(@jakarta.annotation.Nullable String internetAddress) {
    this.internetAddress = internetAddress;
  }

  public MerchantRequest merchantDescriptor(@jakarta.annotation.Nullable String merchantDescriptor) {
    
    this.merchantDescriptor = merchantDescriptor;
    return this;
  }

  /**
   * [Merchant descriptor]
   * @return merchantDescriptor
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MERCHANT_DESCRIPTOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMerchantDescriptor() {
    return merchantDescriptor;
  }


  @JsonProperty(JSON_PROPERTY_MERCHANT_DESCRIPTOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMerchantDescriptor(@jakarta.annotation.Nullable String merchantDescriptor) {
    this.merchantDescriptor = merchantDescriptor;
  }

  public MerchantRequest merchantCategoryCode(@jakarta.annotation.Nonnull String merchantCategoryCode) {
    
    this.merchantCategoryCode = merchantCategoryCode;
    return this;
  }

  /**
   * [A 4 digit code assigned by the merchant’s acquirer to identify the merchant’s type of business.]
   * @return merchantCategoryCode
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MERCHANT_CATEGORY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getMerchantCategoryCode() {
    return merchantCategoryCode;
  }


  @JsonProperty(JSON_PROPERTY_MERCHANT_CATEGORY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMerchantCategoryCode(@jakarta.annotation.Nonnull String merchantCategoryCode) {
    this.merchantCategoryCode = merchantCategoryCode;
  }

  public MerchantRequest merchantLineBusiness(@jakarta.annotation.Nullable String merchantLineBusiness) {
    
    this.merchantLineBusiness = merchantLineBusiness;
    return this;
  }

  /**
   * [Merchant line business]
   * @return merchantLineBusiness
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MERCHANT_LINE_BUSINESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMerchantLineBusiness() {
    return merchantLineBusiness;
  }


  @JsonProperty(JSON_PROPERTY_MERCHANT_LINE_BUSINESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMerchantLineBusiness(@jakarta.annotation.Nullable String merchantLineBusiness) {
    this.merchantLineBusiness = merchantLineBusiness;
  }

  public MerchantRequest merchantAcquiringIdentifiers(@jakarta.annotation.Nonnull List<String> merchantAcquiringIdentifiers) {
    
    this.merchantAcquiringIdentifiers = merchantAcquiringIdentifiers;
    return this;
  }

  public MerchantRequest addMerchantAcquiringIdentifiersItem(String merchantAcquiringIdentifiersItem) {
    if (this.merchantAcquiringIdentifiers == null) {
      this.merchantAcquiringIdentifiers = new ArrayList<>();
    }
    this.merchantAcquiringIdentifiers.add(merchantAcquiringIdentifiersItem);
    return this;
  }

  /**
   * [Merchant acquiring identifier]
   * @return merchantAcquiringIdentifiers
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MERCHANT_ACQUIRING_IDENTIFIERS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<String> getMerchantAcquiringIdentifiers() {
    return merchantAcquiringIdentifiers;
  }


  @JsonProperty(JSON_PROPERTY_MERCHANT_ACQUIRING_IDENTIFIERS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMerchantAcquiringIdentifiers(@jakarta.annotation.Nonnull List<String> merchantAcquiringIdentifiers) {
    this.merchantAcquiringIdentifiers = merchantAcquiringIdentifiers;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MerchantRequest merchantRequest = (MerchantRequest) o;
    return Objects.equals(this.city, merchantRequest.city) &&
        Objects.equals(this.state, merchantRequest.state) &&
        Objects.equals(this.merchantId, merchantRequest.merchantId) &&
        Objects.equals(this.postalCode, merchantRequest.postalCode) &&
        Objects.equals(this.contactName, merchantRequest.contactName) &&
        Objects.equals(this.countryCode, merchantRequest.countryCode) &&
        Objects.equals(this.contactEmail, merchantRequest.contactEmail) &&
        Objects.equals(this.contactPhone, merchantRequest.contactPhone) &&
        Objects.equals(this.merchantName, merchantRequest.merchantName) &&
        Objects.equals(this.parentCompany, merchantRequest.parentCompany) &&
        Objects.equals(this.cardAcceptorId, merchantRequest.cardAcceptorId) &&
        Objects.equals(this.streetAddress1, merchantRequest.streetAddress1) &&
        Objects.equals(this.streetAddress2, merchantRequest.streetAddress2) &&
        Objects.equals(this.internetAddress, merchantRequest.internetAddress) &&
        Objects.equals(this.merchantDescriptor, merchantRequest.merchantDescriptor) &&
        Objects.equals(this.merchantCategoryCode, merchantRequest.merchantCategoryCode) &&
        Objects.equals(this.merchantLineBusiness, merchantRequest.merchantLineBusiness) &&
        Objects.equals(this.merchantAcquiringIdentifiers, merchantRequest.merchantAcquiringIdentifiers);
  }

  @Override
  public int hashCode() {
    return Objects.hash(city, state, merchantId, postalCode, contactName, countryCode, contactEmail, contactPhone, merchantName, parentCompany, cardAcceptorId, streetAddress1, streetAddress2, internetAddress, merchantDescriptor, merchantCategoryCode, merchantLineBusiness, merchantAcquiringIdentifiers);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MerchantRequest {\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    merchantId: ").append(toIndentedString(merchantId)).append("\n");
    sb.append("    postalCode: ").append(toIndentedString(postalCode)).append("\n");
    sb.append("    contactName: ").append(toIndentedString(contactName)).append("\n");
    sb.append("    countryCode: ").append(toIndentedString(countryCode)).append("\n");
    sb.append("    contactEmail: ").append(toIndentedString(contactEmail)).append("\n");
    sb.append("    contactPhone: ").append(toIndentedString(contactPhone)).append("\n");
    sb.append("    merchantName: ").append(toIndentedString(merchantName)).append("\n");
    sb.append("    parentCompany: ").append(toIndentedString(parentCompany)).append("\n");
    sb.append("    cardAcceptorId: ").append(toIndentedString(cardAcceptorId)).append("\n");
    sb.append("    streetAddress1: ").append(toIndentedString(streetAddress1)).append("\n");
    sb.append("    streetAddress2: ").append(toIndentedString(streetAddress2)).append("\n");
    sb.append("    internetAddress: ").append(toIndentedString(internetAddress)).append("\n");
    sb.append("    merchantDescriptor: ").append(toIndentedString(merchantDescriptor)).append("\n");
    sb.append("    merchantCategoryCode: ").append(toIndentedString(merchantCategoryCode)).append("\n");
    sb.append("    merchantLineBusiness: ").append(toIndentedString(merchantLineBusiness)).append("\n");
    sb.append("    merchantAcquiringIdentifiers: ").append(toIndentedString(merchantAcquiringIdentifiers)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

