/*
 * Visa Account Updater
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * [Rejected Inquiry Response body]
 */
@JsonPropertyOrder({
  RejectedInquiryResponse.JSON_PROPERTY_REJECT_REASON,
  RejectedInquiryResponse.JSON_PROPERTY_EXPIRATION_DATE,
  RejectedInquiryResponse.JSON_PROPERTY_REJECT_REASON_CODE,
  RejectedInquiryResponse.JSON_PROPERTY_CARDHOLDER_ACCOUNT_NUMBER
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-29T11:09:21.433785600+01:00[Africa/Casablanca]", comments = "Generator version: 7.12.0")
public class RejectedInquiryResponse {
  public static final String JSON_PROPERTY_REJECT_REASON = "rejectReason";
  @jakarta.annotation.Nullable
  private String rejectReason;

  public static final String JSON_PROPERTY_EXPIRATION_DATE = "expirationDate";
  @jakarta.annotation.Nullable
  private String expirationDate;

  public static final String JSON_PROPERTY_REJECT_REASON_CODE = "rejectReasonCode";
  @jakarta.annotation.Nullable
  private String rejectReasonCode;

  public static final String JSON_PROPERTY_CARDHOLDER_ACCOUNT_NUMBER = "cardholderAccountNumber";
  @jakarta.annotation.Nonnull
  private String cardholderAccountNumber;

  public RejectedInquiryResponse() {
  }

  public RejectedInquiryResponse rejectReason(@jakarta.annotation.Nullable String rejectReason) {
    
    this.rejectReason = rejectReason;
    return this;
  }

  /**
   * [This field contains the description of the reject code: * 1—Account Number does not start with 2, 3, 4, 5 or 6 * 3—Account Number contains non-numeric characters or is blank * 4—Account Number is not of proper length (must be 13, 15, 16 or 19) * 5—Expiration Date is invalid (must be YYMM)] 
   * @return rejectReason
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REJECT_REASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRejectReason() {
    return rejectReason;
  }


  @JsonProperty(JSON_PROPERTY_REJECT_REASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRejectReason(@jakarta.annotation.Nullable String rejectReason) {
    this.rejectReason = rejectReason;
  }

  public RejectedInquiryResponse expirationDate(@jakarta.annotation.Nullable String expirationDate) {
    
    this.expirationDate = expirationDate;
    return this;
  }

  /**
   * [This field contains the old expiration date in YYMM format, where YY &#x3D; 00-99 and MM &#x3D; 01–12]
   * @return expirationDate
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXPIRATION_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getExpirationDate() {
    return expirationDate;
  }


  @JsonProperty(JSON_PROPERTY_EXPIRATION_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExpirationDate(@jakarta.annotation.Nullable String expirationDate) {
    this.expirationDate = expirationDate;
  }

  public RejectedInquiryResponse rejectReasonCode(@jakarta.annotation.Nullable String rejectReasonCode) {
    
    this.rejectReasonCode = rejectReasonCode;
    return this;
  }

  /**
   * [This field contains one of the following codes: * 1—Account Number does not start with 2, 3, 4, 5 or 6 * 3—Account Number contains non-numeric characters or is blank * 4—Account Number is not of proper length (must be 13, 15, 16 or 19) * 5—Expiration Date is invalid (must be YYMM)] 
   * @return rejectReasonCode
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REJECT_REASON_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRejectReasonCode() {
    return rejectReasonCode;
  }


  @JsonProperty(JSON_PROPERTY_REJECT_REASON_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRejectReasonCode(@jakarta.annotation.Nullable String rejectReasonCode) {
    this.rejectReasonCode = rejectReasonCode;
  }

  public RejectedInquiryResponse cardholderAccountNumber(@jakarta.annotation.Nonnull String cardholderAccountNumber) {
    
    this.cardholderAccountNumber = cardholderAccountNumber;
    return this;
  }

  /**
   * [This field contains the account number that was submitted in the associated Acquirer Inquiry Request.]
   * @return cardholderAccountNumber
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CARDHOLDER_ACCOUNT_NUMBER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCardholderAccountNumber() {
    return cardholderAccountNumber;
  }


  @JsonProperty(JSON_PROPERTY_CARDHOLDER_ACCOUNT_NUMBER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCardholderAccountNumber(@jakarta.annotation.Nonnull String cardholderAccountNumber) {
    this.cardholderAccountNumber = cardholderAccountNumber;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RejectedInquiryResponse rejectedInquiryResponse = (RejectedInquiryResponse) o;
    return Objects.equals(this.rejectReason, rejectedInquiryResponse.rejectReason) &&
        Objects.equals(this.expirationDate, rejectedInquiryResponse.expirationDate) &&
        Objects.equals(this.rejectReasonCode, rejectedInquiryResponse.rejectReasonCode) &&
        Objects.equals(this.cardholderAccountNumber, rejectedInquiryResponse.cardholderAccountNumber);
  }

  @Override
  public int hashCode() {
    return Objects.hash(rejectReason, expirationDate, rejectReasonCode, cardholderAccountNumber);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RejectedInquiryResponse {\n");
    sb.append("    rejectReason: ").append(toIndentedString(rejectReason)).append("\n");
    sb.append("    expirationDate: ").append(toIndentedString(expirationDate)).append("\n");
    sb.append("    rejectReasonCode: ").append(toIndentedString(rejectReasonCode)).append("\n");
    sb.append("    cardholderAccountNumber: ").append(toIndentedString(cardholderAccountNumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

