/*
 * Visa Account Updater
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.LocalDate;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * [RejectedStopAdviceResponse]
 */
@JsonPropertyOrder({
  RejectedStopAdviceResponse.JSON_PROPERTY_START_DATE,
  RejectedStopAdviceResponse.JSON_PROPERTY_REJECT_CODE,
  RejectedStopAdviceResponse.JSON_PROPERTY_MERCHANT_NAME,
  RejectedStopAdviceResponse.JSON_PROPERTY_REJECT_MESSAGE,
  RejectedStopAdviceResponse.JSON_PROPERTY_CARD_ACCEPTOR_ID,
  RejectedStopAdviceResponse.JSON_PROPERTY_CARDHOLDER_ACCOUNT_NUMBER
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-29T11:09:21.433785600+01:00[Africa/Casablanca]", comments = "Generator version: 7.12.0")
public class RejectedStopAdviceResponse {
  public static final String JSON_PROPERTY_START_DATE = "startDate";
  @jakarta.annotation.Nullable
  private LocalDate startDate;

  public static final String JSON_PROPERTY_REJECT_CODE = "rejectCode";
  @jakarta.annotation.Nullable
  private String rejectCode;

  public static final String JSON_PROPERTY_MERCHANT_NAME = "merchantName";
  @jakarta.annotation.Nonnull
  private String merchantName;

  public static final String JSON_PROPERTY_REJECT_MESSAGE = "rejectMessage";
  @jakarta.annotation.Nullable
  private String rejectMessage;

  public static final String JSON_PROPERTY_CARD_ACCEPTOR_ID = "cardAcceptorId";
  @jakarta.annotation.Nonnull
  private String cardAcceptorId;

  public static final String JSON_PROPERTY_CARDHOLDER_ACCOUNT_NUMBER = "cardholderAccountNumber";
  @jakarta.annotation.Nonnull
  private String cardholderAccountNumber;

  public RejectedStopAdviceResponse() {
  }

  public RejectedStopAdviceResponse startDate(@jakarta.annotation.Nullable LocalDate startDate) {
    
    this.startDate = startDate;
    return this;
  }

  /**
   * [This field contains the start date, which shouldn&#39;t be less than the current date, and its format is yyyy-mm-dd, the default value is the current date.]
   * @return startDate
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_START_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LocalDate getStartDate() {
    return startDate;
  }


  @JsonProperty(JSON_PROPERTY_START_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStartDate(@jakarta.annotation.Nullable LocalDate startDate) {
    this.startDate = startDate;
  }

  public RejectedStopAdviceResponse rejectCode(@jakarta.annotation.Nullable String rejectCode) {
    
    this.rejectCode = rejectCode;
    return this;
  }

  /**
   * [This field contains one of the following reject codes: * H—Account number does not start with 2, 3, 4, 5 or 6 * G—Account number contains non-numeric characters or is blank * L—Account number is not of proper length (must be 13, 15, 16 or 19) * M—Account number is not mod 10 compliant * N—No stop advice applied, unable to find merchant information for the requested card acceptor id * R—Account number is not associated with requested segment id * S—Start date must not be less than the current date * D—Duplicate stop advice in the request * I—Mandatory field cardholderAccountNumber is missing or blank in the request * J—Mandatory field cardAcceptorId is missing or blank in the request * K—Mandatory field merchantName is missing or blank in the request * F—Stop advice is already placed for requested account number and merchant] 
   * @return rejectCode
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REJECT_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRejectCode() {
    return rejectCode;
  }


  @JsonProperty(JSON_PROPERTY_REJECT_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRejectCode(@jakarta.annotation.Nullable String rejectCode) {
    this.rejectCode = rejectCode;
  }

  public RejectedStopAdviceResponse merchantName(@jakarta.annotation.Nonnull String merchantName) {
    
    this.merchantName = merchantName;
    return this;
  }

  /**
   * [This field must contain merchant name.]
   * @return merchantName
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MERCHANT_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getMerchantName() {
    return merchantName;
  }


  @JsonProperty(JSON_PROPERTY_MERCHANT_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMerchantName(@jakarta.annotation.Nonnull String merchantName) {
    this.merchantName = merchantName;
  }

  public RejectedStopAdviceResponse rejectMessage(@jakarta.annotation.Nullable String rejectMessage) {
    
    this.rejectMessage = rejectMessage;
    return this;
  }

  /**
   * [This field contains the description of reject message: * H—Account number does not start with 2, 3, 4, 5 or 6 * G—Account number contains non-numeric characters or is blank * L—Account number is not of proper length (must be 13, 15, 16 or 19) * M—Account number is not mod 10 compliant * N—No stop advice applied, unable to find merchant information for the requested card acceptor id * R—Account number is not associated with requested segment id * S—Start date must not be less than the current date * D—Duplicate stop advice in the request * I—Mandatory field cardholderAccountNumber is missing or blank in the request * J—Mandatory field cardAcceptorId is missing or blank in the request * K—Mandatory field merchantName is missing or blank in the request * F—Stop advice is already placed for requested account number and merchant] 
   * @return rejectMessage
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REJECT_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRejectMessage() {
    return rejectMessage;
  }


  @JsonProperty(JSON_PROPERTY_REJECT_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRejectMessage(@jakarta.annotation.Nullable String rejectMessage) {
    this.rejectMessage = rejectMessage;
  }

  public RejectedStopAdviceResponse cardAcceptorId(@jakarta.annotation.Nonnull String cardAcceptorId) {
    
    this.cardAcceptorId = cardAcceptorId;
    return this;
  }

  /**
   * [This field must contain card acceptor id.]
   * @return cardAcceptorId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CARD_ACCEPTOR_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCardAcceptorId() {
    return cardAcceptorId;
  }


  @JsonProperty(JSON_PROPERTY_CARD_ACCEPTOR_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCardAcceptorId(@jakarta.annotation.Nonnull String cardAcceptorId) {
    this.cardAcceptorId = cardAcceptorId;
  }

  public RejectedStopAdviceResponse cardholderAccountNumber(@jakarta.annotation.Nonnull String cardholderAccountNumber) {
    
    this.cardholderAccountNumber = cardholderAccountNumber;
    return this;
  }

  /**
   * [This field must contain the account number (Visa, Mastercard, American Express, or Discover).]
   * @return cardholderAccountNumber
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CARDHOLDER_ACCOUNT_NUMBER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCardholderAccountNumber() {
    return cardholderAccountNumber;
  }


  @JsonProperty(JSON_PROPERTY_CARDHOLDER_ACCOUNT_NUMBER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCardholderAccountNumber(@jakarta.annotation.Nonnull String cardholderAccountNumber) {
    this.cardholderAccountNumber = cardholderAccountNumber;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RejectedStopAdviceResponse rejectedStopAdviceResponse = (RejectedStopAdviceResponse) o;
    return Objects.equals(this.startDate, rejectedStopAdviceResponse.startDate) &&
        Objects.equals(this.rejectCode, rejectedStopAdviceResponse.rejectCode) &&
        Objects.equals(this.merchantName, rejectedStopAdviceResponse.merchantName) &&
        Objects.equals(this.rejectMessage, rejectedStopAdviceResponse.rejectMessage) &&
        Objects.equals(this.cardAcceptorId, rejectedStopAdviceResponse.cardAcceptorId) &&
        Objects.equals(this.cardholderAccountNumber, rejectedStopAdviceResponse.cardholderAccountNumber);
  }

  @Override
  public int hashCode() {
    return Objects.hash(startDate, rejectCode, merchantName, rejectMessage, cardAcceptorId, cardholderAccountNumber);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RejectedStopAdviceResponse {\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("    rejectCode: ").append(toIndentedString(rejectCode)).append("\n");
    sb.append("    merchantName: ").append(toIndentedString(merchantName)).append("\n");
    sb.append("    rejectMessage: ").append(toIndentedString(rejectMessage)).append("\n");
    sb.append("    cardAcceptorId: ").append(toIndentedString(cardAcceptorId)).append("\n");
    sb.append("    cardholderAccountNumber: ").append(toIndentedString(cardholderAccountNumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

