/*
 * Visa Account Updater
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * [Rejected Subscription Response]
 */
@JsonPropertyOrder({
  RejectedSubscription.JSON_PROPERTY_REJECT_REASON,
  RejectedSubscription.JSON_PROPERTY_REJECT_REASON_CODE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-29T11:09:21.433785600+01:00[Africa/Casablanca]", comments = "Generator version: 7.12.0")
public class RejectedSubscription {
  public static final String JSON_PROPERTY_REJECT_REASON = "rejectReason";
  @jakarta.annotation.Nonnull
  private String rejectReason;

  public static final String JSON_PROPERTY_REJECT_REASON_CODE = "rejectReasonCode";
  @jakarta.annotation.Nonnull
  private String rejectReasonCode;

  public RejectedSubscription() {
  }

  public RejectedSubscription rejectReason(@jakarta.annotation.Nonnull String rejectReason) {
    
    this.rejectReason = rejectReason;
    return this;
  }

  /**
   * [This field contains the description of the reject code: * 1-Account Number does not start with 2, 3, 4, 5 or 6 * 3-Account Number contains non-numeric characters or is blank * 4-Account Number is not of proper length (must be 13, 15, 16 or 19 * M—Account number is not mod 10 compliant * D-Duplicate subscription in the request] 
   * @return rejectReason
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_REJECT_REASON)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getRejectReason() {
    return rejectReason;
  }


  @JsonProperty(JSON_PROPERTY_REJECT_REASON)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRejectReason(@jakarta.annotation.Nonnull String rejectReason) {
    this.rejectReason = rejectReason;
  }

  public RejectedSubscription rejectReasonCode(@jakarta.annotation.Nonnull String rejectReasonCode) {
    
    this.rejectReasonCode = rejectReasonCode;
    return this;
  }

  /**
   * [This field contains one of the following codes: * 1-Account Number does not start with 2, 3, 4, 5 or 6 * 3-Account Number contains non-numeric characters or is blank * 4-Account Number is not of proper length (must be 13, 15, 16 or 19 * M—Account number is not mod 10 compliant * D-Duplicate subscription in the request] 
   * @return rejectReasonCode
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_REJECT_REASON_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getRejectReasonCode() {
    return rejectReasonCode;
  }


  @JsonProperty(JSON_PROPERTY_REJECT_REASON_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRejectReasonCode(@jakarta.annotation.Nonnull String rejectReasonCode) {
    this.rejectReasonCode = rejectReasonCode;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RejectedSubscription rejectedSubscription = (RejectedSubscription) o;
    return Objects.equals(this.rejectReason, rejectedSubscription.rejectReason) &&
        Objects.equals(this.rejectReasonCode, rejectedSubscription.rejectReasonCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(rejectReason, rejectReasonCode);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RejectedSubscription {\n");
    sb.append("    rejectReason: ").append(toIndentedString(rejectReason)).append("\n");
    sb.append("    rejectReasonCode: ").append(toIndentedString(rejectReasonCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

