/*
 * Visa Account Updater
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * [Reject Request]
 */
@JsonPropertyOrder({
  RejectedRequestResponse.JSON_PROPERTY_MERCHANT_ID,
  RejectedRequestResponse.JSON_PROPERTY_REJECT_REASON,
  RejectedRequestResponse.JSON_PROPERTY_SUB_MERCHANT_NAME,
  RejectedRequestResponse.JSON_PROPERTY_REJECT_REASON_CODE,
  RejectedRequestResponse.JSON_PROPERTY_ACQUIRER_SEGMENT_ID
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-29T11:09:21.433785600+01:00[Africa/Casablanca]", comments = "Generator version: 7.12.0")
public class RejectedRequestResponse {
  public static final String JSON_PROPERTY_MERCHANT_ID = "merchantId";
  @jakarta.annotation.Nonnull
  private String merchantId;

  public static final String JSON_PROPERTY_REJECT_REASON = "rejectReason";
  @jakarta.annotation.Nonnull
  private String rejectReason;

  public static final String JSON_PROPERTY_SUB_MERCHANT_NAME = "subMerchantName";
  @jakarta.annotation.Nullable
  private String subMerchantName;

  public static final String JSON_PROPERTY_REJECT_REASON_CODE = "rejectReasonCode";
  @jakarta.annotation.Nonnull
  private String rejectReasonCode;

  public static final String JSON_PROPERTY_ACQUIRER_SEGMENT_ID = "acquirerSegmentId";
  @jakarta.annotation.Nonnull
  private Integer acquirerSegmentId;

  public RejectedRequestResponse() {
  }

  public RejectedRequestResponse merchantId(@jakarta.annotation.Nonnull String merchantId) {
    
    this.merchantId = merchantId;
    return this;
  }

  /**
   * [Acquirer assigns the merchant ID. This field must contain a valid VAU Merchant ID.]
   * @return merchantId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MERCHANT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getMerchantId() {
    return merchantId;
  }


  @JsonProperty(JSON_PROPERTY_MERCHANT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMerchantId(@jakarta.annotation.Nonnull String merchantId) {
    this.merchantId = merchantId;
  }

  public RejectedRequestResponse rejectReason(@jakarta.annotation.Nonnull String rejectReason) {
    
    this.rejectReason = rejectReason;
    return this;
  }

  /**
   * [This field contains the description of the reject code: * A—Acquirer segment is not enrolled * X-Acquirer status is in test mode, please contact client services representative * M—Merchant is not enrolled or inactive * V—No data found in subscription field * 9—Max subscription threshold passed for single request, current threshold is:100.] 
   * @return rejectReason
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_REJECT_REASON)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getRejectReason() {
    return rejectReason;
  }


  @JsonProperty(JSON_PROPERTY_REJECT_REASON)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRejectReason(@jakarta.annotation.Nonnull String rejectReason) {
    this.rejectReason = rejectReason;
  }

  public RejectedRequestResponse subMerchantName(@jakarta.annotation.Nullable String subMerchantName) {
    
    this.subMerchantName = subMerchantName;
    return this;
  }

  /**
   * [If inquiry is submitted by a merchant, then this field must be empty. If inquiry is submitted by a third-party aggregator on behalf of a merchant, then this field must be populated with the sub- merchant name. Acquirers and processors must pass the value to Visa. No special characters are allowed.]
   * @return subMerchantName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SUB_MERCHANT_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSubMerchantName() {
    return subMerchantName;
  }


  @JsonProperty(JSON_PROPERTY_SUB_MERCHANT_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSubMerchantName(@jakarta.annotation.Nullable String subMerchantName) {
    this.subMerchantName = subMerchantName;
  }

  public RejectedRequestResponse rejectReasonCode(@jakarta.annotation.Nonnull String rejectReasonCode) {
    
    this.rejectReasonCode = rejectReasonCode;
    return this;
  }

  /**
   * [This field contains one of the following codes: * A—Acquirer segment is not enrolled * X-Acquirer status is in test mode, please contact client services representative * M—Merchant is not enrolled or inactive * V—No data found in subscription field * 9—Max subscription threshold passed for single request, current threshold is:100\&quot;.] 
   * @return rejectReasonCode
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_REJECT_REASON_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getRejectReasonCode() {
    return rejectReasonCode;
  }


  @JsonProperty(JSON_PROPERTY_REJECT_REASON_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRejectReasonCode(@jakarta.annotation.Nonnull String rejectReasonCode) {
    this.rejectReasonCode = rejectReasonCode;
  }

  public RejectedRequestResponse acquirerSegmentId(@jakarta.annotation.Nonnull Integer acquirerSegmentId) {
    
    this.acquirerSegmentId = acquirerSegmentId;
    return this;
  }

  /**
   * [This field  must contain a valid VAU Acquirer Segment ID.]
   * @return acquirerSegmentId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ACQUIRER_SEGMENT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getAcquirerSegmentId() {
    return acquirerSegmentId;
  }


  @JsonProperty(JSON_PROPERTY_ACQUIRER_SEGMENT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAcquirerSegmentId(@jakarta.annotation.Nonnull Integer acquirerSegmentId) {
    this.acquirerSegmentId = acquirerSegmentId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RejectedRequestResponse rejectedRequestResponse = (RejectedRequestResponse) o;
    return Objects.equals(this.merchantId, rejectedRequestResponse.merchantId) &&
        Objects.equals(this.rejectReason, rejectedRequestResponse.rejectReason) &&
        Objects.equals(this.subMerchantName, rejectedRequestResponse.subMerchantName) &&
        Objects.equals(this.rejectReasonCode, rejectedRequestResponse.rejectReasonCode) &&
        Objects.equals(this.acquirerSegmentId, rejectedRequestResponse.acquirerSegmentId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(merchantId, rejectReason, subMerchantName, rejectReasonCode, acquirerSegmentId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RejectedRequestResponse {\n");
    sb.append("    merchantId: ").append(toIndentedString(merchantId)).append("\n");
    sb.append("    rejectReason: ").append(toIndentedString(rejectReason)).append("\n");
    sb.append("    subMerchantName: ").append(toIndentedString(subMerchantName)).append("\n");
    sb.append("    rejectReasonCode: ").append(toIndentedString(rejectReasonCode)).append("\n");
    sb.append("    acquirerSegmentId: ").append(toIndentedString(acquirerSegmentId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

