/*
 * Visa Account Updater
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * [Reject Request]
 */
@JsonPropertyOrder({
  RejectedStopAdviceRequestResponse.JSON_PROPERTY_REJECT_REASON,
  RejectedStopAdviceRequestResponse.JSON_PROPERTY_ISSUER_SEGMENT_ID,
  RejectedStopAdviceRequestResponse.JSON_PROPERTY_REJECT_REASON_CODE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-29T11:09:21.433785600+01:00[Africa/Casablanca]", comments = "Generator version: 7.12.0")
public class RejectedStopAdviceRequestResponse {
  public static final String JSON_PROPERTY_REJECT_REASON = "rejectReason";
  @jakarta.annotation.Nullable
  private String rejectReason;

  public static final String JSON_PROPERTY_ISSUER_SEGMENT_ID = "issuerSegmentId";
  @jakarta.annotation.Nonnull
  private Integer issuerSegmentId;

  public static final String JSON_PROPERTY_REJECT_REASON_CODE = "rejectReasonCode";
  @jakarta.annotation.Nullable
  private String rejectReasonCode;

  public RejectedStopAdviceRequestResponse() {
  }

  public RejectedStopAdviceRequestResponse rejectReason(@jakarta.annotation.Nullable String rejectReason) {
    
    this.rejectReason = rejectReason;
    return this;
  }

  /**
   * [This field contains the description of the reject code: * A—Issuer segment is not enrolled * T—Max stop advices threshold passed for single request, current threshold is:100 * V—No data found in stop advice field 
   * @return rejectReason
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REJECT_REASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRejectReason() {
    return rejectReason;
  }


  @JsonProperty(JSON_PROPERTY_REJECT_REASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRejectReason(@jakarta.annotation.Nullable String rejectReason) {
    this.rejectReason = rejectReason;
  }

  public RejectedStopAdviceRequestResponse issuerSegmentId(@jakarta.annotation.Nonnull Integer issuerSegmentId) {
    
    this.issuerSegmentId = issuerSegmentId;
    return this;
  }

  /**
   * [This field must contain a valid VAU Issuer Segment ID.]
   * @return issuerSegmentId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ISSUER_SEGMENT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getIssuerSegmentId() {
    return issuerSegmentId;
  }


  @JsonProperty(JSON_PROPERTY_ISSUER_SEGMENT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIssuerSegmentId(@jakarta.annotation.Nonnull Integer issuerSegmentId) {
    this.issuerSegmentId = issuerSegmentId;
  }

  public RejectedStopAdviceRequestResponse rejectReasonCode(@jakarta.annotation.Nullable String rejectReasonCode) {
    
    this.rejectReasonCode = rejectReasonCode;
    return this;
  }

  /**
   * [This field contains one of the following codes: * A—Issuer segment is not enrolled * T—Max stop advices threshold passed for single request, current threshold is:100 * V—No data found in stop advice field 
   * @return rejectReasonCode
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REJECT_REASON_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRejectReasonCode() {
    return rejectReasonCode;
  }


  @JsonProperty(JSON_PROPERTY_REJECT_REASON_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRejectReasonCode(@jakarta.annotation.Nullable String rejectReasonCode) {
    this.rejectReasonCode = rejectReasonCode;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RejectedStopAdviceRequestResponse rejectedStopAdviceRequestResponse = (RejectedStopAdviceRequestResponse) o;
    return Objects.equals(this.rejectReason, rejectedStopAdviceRequestResponse.rejectReason) &&
        Objects.equals(this.issuerSegmentId, rejectedStopAdviceRequestResponse.issuerSegmentId) &&
        Objects.equals(this.rejectReasonCode, rejectedStopAdviceRequestResponse.rejectReasonCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(rejectReason, issuerSegmentId, rejectReasonCode);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RejectedStopAdviceRequestResponse {\n");
    sb.append("    rejectReason: ").append(toIndentedString(rejectReason)).append("\n");
    sb.append("    issuerSegmentId: ").append(toIndentedString(issuerSegmentId)).append("\n");
    sb.append("    rejectReasonCode: ").append(toIndentedString(rejectReasonCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

