/*
 * Visa Account Updater
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.Inquiry;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * [Acquirer-api request body]
 */
@JsonPropertyOrder({
  Request.JSON_PROPERTY_INQUIRIES,
  Request.JSON_PROPERTY_MERCHANT_ID,
  Request.JSON_PROPERTY_SUB_MERCHANT_NAME,
  Request.JSON_PROPERTY_ACQUIRER_SEGMENT_ID,
  Request.JSON_PROPERTY_ACQUIRER_OR_MERCHANT_PROPRIETARY_INFO
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-29T11:09:21.433785600+01:00[Africa/Casablanca]", comments = "Generator version: 7.12.0")
public class Request {
  public static final String JSON_PROPERTY_INQUIRIES = "inquiries";
  @jakarta.annotation.Nonnull
  private List<Inquiry> inquiries = new ArrayList<>();

  public static final String JSON_PROPERTY_MERCHANT_ID = "merchantId";
  @jakarta.annotation.Nonnull
  private String merchantId;

  public static final String JSON_PROPERTY_SUB_MERCHANT_NAME = "subMerchantName";
  @jakarta.annotation.Nullable
  private String subMerchantName;

  public static final String JSON_PROPERTY_ACQUIRER_SEGMENT_ID = "acquirerSegmentId";
  @jakarta.annotation.Nonnull
  private Integer acquirerSegmentId;

  public static final String JSON_PROPERTY_ACQUIRER_OR_MERCHANT_PROPRIETARY_INFO = "acquirerOrMerchantProprietaryInfo";
  @jakarta.annotation.Nullable
  private String acquirerOrMerchantProprietaryInfo;

  public Request() {
  }

  public Request inquiries(@jakarta.annotation.Nonnull List<Inquiry> inquiries) {
    
    this.inquiries = inquiries;
    return this;
  }

  public Request addInquiriesItem(Inquiry inquiriesItem) {
    if (this.inquiries == null) {
      this.inquiries = new ArrayList<>();
    }
    this.inquiries.add(inquiriesItem);
    return this;
  }

  /**
   * [List of Inquiries]
   * @return inquiries
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_INQUIRIES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<Inquiry> getInquiries() {
    return inquiries;
  }


  @JsonProperty(JSON_PROPERTY_INQUIRIES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setInquiries(@jakarta.annotation.Nonnull List<Inquiry> inquiries) {
    this.inquiries = inquiries;
  }

  public Request merchantId(@jakarta.annotation.Nonnull String merchantId) {
    
    this.merchantId = merchantId;
    return this;
  }

  /**
   * [Acquirer assigns the merchant ID. This field must contain a valid VAU Merchant ID.]
   * @return merchantId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MERCHANT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getMerchantId() {
    return merchantId;
  }


  @JsonProperty(JSON_PROPERTY_MERCHANT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMerchantId(@jakarta.annotation.Nonnull String merchantId) {
    this.merchantId = merchantId;
  }

  public Request subMerchantName(@jakarta.annotation.Nullable String subMerchantName) {
    
    this.subMerchantName = subMerchantName;
    return this;
  }

  /**
   * [If inquiry is submitted by a merchant, then this field must be empty. If inquiry is submitted by a third-party aggregator on behalf of a merchant, then this field must be populated with the sub-merchant name. Acquirers and processors must pass the value to Visa. No special characters are allowed.]
   * @return subMerchantName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SUB_MERCHANT_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSubMerchantName() {
    return subMerchantName;
  }


  @JsonProperty(JSON_PROPERTY_SUB_MERCHANT_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSubMerchantName(@jakarta.annotation.Nullable String subMerchantName) {
    this.subMerchantName = subMerchantName;
  }

  public Request acquirerSegmentId(@jakarta.annotation.Nonnull Integer acquirerSegmentId) {
    
    this.acquirerSegmentId = acquirerSegmentId;
    return this;
  }

  /**
   * [This field must contain a valid VAU Acquirer Segment ID.]
   * @return acquirerSegmentId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ACQUIRER_SEGMENT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getAcquirerSegmentId() {
    return acquirerSegmentId;
  }


  @JsonProperty(JSON_PROPERTY_ACQUIRER_SEGMENT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAcquirerSegmentId(@jakarta.annotation.Nonnull Integer acquirerSegmentId) {
    this.acquirerSegmentId = acquirerSegmentId;
  }

  public Request acquirerOrMerchantProprietaryInfo(@jakarta.annotation.Nullable String acquirerOrMerchantProprietaryInfo) {
    
    this.acquirerOrMerchantProprietaryInfo = acquirerOrMerchantProprietaryInfo;
    return this;
  }

  /**
   * [If provided, it contains acquirer or merchant proprietary information such as a customer ID that is carried in the merchant’s back-end system.]
   * @return acquirerOrMerchantProprietaryInfo
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ACQUIRER_OR_MERCHANT_PROPRIETARY_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAcquirerOrMerchantProprietaryInfo() {
    return acquirerOrMerchantProprietaryInfo;
  }


  @JsonProperty(JSON_PROPERTY_ACQUIRER_OR_MERCHANT_PROPRIETARY_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAcquirerOrMerchantProprietaryInfo(@jakarta.annotation.Nullable String acquirerOrMerchantProprietaryInfo) {
    this.acquirerOrMerchantProprietaryInfo = acquirerOrMerchantProprietaryInfo;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Request request = (Request) o;
    return Objects.equals(this.inquiries, request.inquiries) &&
        Objects.equals(this.merchantId, request.merchantId) &&
        Objects.equals(this.subMerchantName, request.subMerchantName) &&
        Objects.equals(this.acquirerSegmentId, request.acquirerSegmentId) &&
        Objects.equals(this.acquirerOrMerchantProprietaryInfo, request.acquirerOrMerchantProprietaryInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(inquiries, merchantId, subMerchantName, acquirerSegmentId, acquirerOrMerchantProprietaryInfo);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Request {\n");
    sb.append("    inquiries: ").append(toIndentedString(inquiries)).append("\n");
    sb.append("    merchantId: ").append(toIndentedString(merchantId)).append("\n");
    sb.append("    subMerchantName: ").append(toIndentedString(subMerchantName)).append("\n");
    sb.append("    acquirerSegmentId: ").append(toIndentedString(acquirerSegmentId)).append("\n");
    sb.append("    acquirerOrMerchantProprietaryInfo: ").append(toIndentedString(acquirerOrMerchantProprietaryInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

