/*
 * Visa Account Updater
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.InquirySubscriptionAttributes;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * [Subscription Inquiry api request body]
 */
@JsonPropertyOrder({
  SubscriptionInquiryRequest.JSON_PROPERTY_MERCHANT_ID,
  SubscriptionInquiryRequest.JSON_PROPERTY_SUBSCRIPTIONS,
  SubscriptionInquiryRequest.JSON_PROPERTY_SUB_MERCHANT_NAME,
  SubscriptionInquiryRequest.JSON_PROPERTY_ACQUIRER_SEGMENT_ID
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-29T11:09:21.433785600+01:00[Africa/Casablanca]", comments = "Generator version: 7.12.0")
public class SubscriptionInquiryRequest {
  public static final String JSON_PROPERTY_MERCHANT_ID = "merchantId";
  @jakarta.annotation.Nonnull
  private String merchantId;

  public static final String JSON_PROPERTY_SUBSCRIPTIONS = "subscriptions";
  @jakarta.annotation.Nonnull
  private List<InquirySubscriptionAttributes> subscriptions = new ArrayList<>();

  public static final String JSON_PROPERTY_SUB_MERCHANT_NAME = "subMerchantName";
  @jakarta.annotation.Nullable
  private String subMerchantName;

  public static final String JSON_PROPERTY_ACQUIRER_SEGMENT_ID = "acquirerSegmentId";
  @jakarta.annotation.Nonnull
  private Integer acquirerSegmentId;

  public SubscriptionInquiryRequest() {
  }

  public SubscriptionInquiryRequest merchantId(@jakarta.annotation.Nonnull String merchantId) {
    
    this.merchantId = merchantId;
    return this;
  }

  /**
   * [Acquirer assigns the merchant ID. This field must contain a valid VAU Merchant ID.]
   * @return merchantId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MERCHANT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getMerchantId() {
    return merchantId;
  }


  @JsonProperty(JSON_PROPERTY_MERCHANT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMerchantId(@jakarta.annotation.Nonnull String merchantId) {
    this.merchantId = merchantId;
  }

  public SubscriptionInquiryRequest subscriptions(@jakarta.annotation.Nonnull List<InquirySubscriptionAttributes> subscriptions) {
    
    this.subscriptions = subscriptions;
    return this;
  }

  public SubscriptionInquiryRequest addSubscriptionsItem(InquirySubscriptionAttributes subscriptionsItem) {
    if (this.subscriptions == null) {
      this.subscriptions = new ArrayList<>();
    }
    this.subscriptions.add(subscriptionsItem);
    return this;
  }

  /**
   * [List of Inquiries]
   * @return subscriptions
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SUBSCRIPTIONS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<InquirySubscriptionAttributes> getSubscriptions() {
    return subscriptions;
  }


  @JsonProperty(JSON_PROPERTY_SUBSCRIPTIONS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSubscriptions(@jakarta.annotation.Nonnull List<InquirySubscriptionAttributes> subscriptions) {
    this.subscriptions = subscriptions;
  }

  public SubscriptionInquiryRequest subMerchantName(@jakarta.annotation.Nullable String subMerchantName) {
    
    this.subMerchantName = subMerchantName;
    return this;
  }

  /**
   * [If inquiry is submitted by a merchant, then this field must be empty. If inquiry is submitted by a third-party aggregator on behalf of a merchant, then this field must be populated with the sub-merchant name. Acquirers and processors must pass the value to Visa. No special characters are allowed.]
   * @return subMerchantName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SUB_MERCHANT_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSubMerchantName() {
    return subMerchantName;
  }


  @JsonProperty(JSON_PROPERTY_SUB_MERCHANT_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSubMerchantName(@jakarta.annotation.Nullable String subMerchantName) {
    this.subMerchantName = subMerchantName;
  }

  public SubscriptionInquiryRequest acquirerSegmentId(@jakarta.annotation.Nonnull Integer acquirerSegmentId) {
    
    this.acquirerSegmentId = acquirerSegmentId;
    return this;
  }

  /**
   * [This field must contain a valid VAU Acquirer Segment ID.]
   * @return acquirerSegmentId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ACQUIRER_SEGMENT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getAcquirerSegmentId() {
    return acquirerSegmentId;
  }


  @JsonProperty(JSON_PROPERTY_ACQUIRER_SEGMENT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAcquirerSegmentId(@jakarta.annotation.Nonnull Integer acquirerSegmentId) {
    this.acquirerSegmentId = acquirerSegmentId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubscriptionInquiryRequest subscriptionInquiryRequest = (SubscriptionInquiryRequest) o;
    return Objects.equals(this.merchantId, subscriptionInquiryRequest.merchantId) &&
        Objects.equals(this.subscriptions, subscriptionInquiryRequest.subscriptions) &&
        Objects.equals(this.subMerchantName, subscriptionInquiryRequest.subMerchantName) &&
        Objects.equals(this.acquirerSegmentId, subscriptionInquiryRequest.acquirerSegmentId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(merchantId, subscriptions, subMerchantName, acquirerSegmentId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubscriptionInquiryRequest {\n");
    sb.append("    merchantId: ").append(toIndentedString(merchantId)).append("\n");
    sb.append("    subscriptions: ").append(toIndentedString(subscriptions)).append("\n");
    sb.append("    subMerchantName: ").append(toIndentedString(subMerchantName)).append("\n");
    sb.append("    acquirerSegmentId: ").append(toIndentedString(acquirerSegmentId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

