/*
 * Visa Account Updater
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.model.SubscriptionDeleteRequest;
import org.openapitools.client.model.SubscriptionDeleteResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.springframework.web.client.RestClientException;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DefaultApi
 */
@Disabled
class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    
    /**
     * Delete PAN subscriptions
     *
     * 
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void subscriptionDeleteUsingPOSTTest() {
        SubscriptionDeleteRequest subscriptionDeleteRequest = null;

        SubscriptionDeleteResponse response = api.subscriptionDeleteUsingPOST(subscriptionDeleteRequest);

        // TODO: test validations
    }
    
}
