/*
 * Visa Account Updater
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.model.BadFormattedErrorMessage;
import org.openapitools.client.model.GenericErrorMessage;
import org.openapitools.client.model.RejectedStopAdviceRequestResponse;
import org.openapitools.client.model.StopAdviceRequest;
import org.openapitools.client.model.StopAdviceResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.springframework.web.client.RestClientException;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for IssuerStopAdviceApiApi
 */
@Disabled
class IssuerStopAdviceApiApiTest {

    private final IssuerStopAdviceApiApi api = new IssuerStopAdviceApiApi();

    
    /**
     * Issuer Stop Advice API
     *
     * Issuer can place stop advice by providing following requested information
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void stopAdviceUsingPOSTTest() {
        StopAdviceRequest stopAdviceRequest = null;
        String accept = null;

        StopAdviceResponse response = api.stopAdviceUsingPOST(stopAdviceRequest, accept);

        // TODO: test validations
    }
    
}
