/*
 * Visa Account Updater
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.model.BadFormattedErrorMessage2;
import org.openapitools.client.model.EncryptedPayload;
import org.openapitools.client.model.GenericErrorMessage;
import org.openapitools.client.model.OutboundResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.springframework.web.client.RestClientException;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PushSubscribeCallbackApiApi
 */
@Disabled
class PushSubscribeCallbackApiApiTest {

    private final PushSubscribeCallbackApiApi api = new PushSubscribeCallbackApiApi();

    
    /**
     * Push Subscribe Callback API
     *
     * Push Subscribe Callback API
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void mockAccountUpdateResponseTest() {
        EncryptedPayload encryptedPayload = null;
        String keyId = null;
        String xCorrelationID = null;
        String accept = null;

        OutboundResponse response = api.mockAccountUpdateResponse(encryptedPayload, keyId, xCorrelationID, accept);

        // TODO: test validations
    }
    
}
