/*
 * Visa Account Updater
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.model.BadFormattedErrorMessage;
import org.openapitools.client.model.GenericErrorMessage;
import org.openapitools.client.model.MerchantEnrolmentRequest;
import org.openapitools.client.model.MerchantEnrolmentResponse;
import org.openapitools.client.model.MerchantSearchRequest;
import org.openapitools.client.model.MerchantSearchResponse;
import org.openapitools.client.model.RejectedMerchantEnrollmentResponse;
import org.openapitools.client.model.RejectedMerchantSearchResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.springframework.web.client.RestClientException;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for VisaAccountUpdaterMerchantApiApi
 */
@Disabled
class VisaAccountUpdaterMerchantApiApiTest {

    private final VisaAccountUpdaterMerchantApiApi api = new VisaAccountUpdaterMerchantApiApi();

    
    /**
     * Merchant Enrollment
     *
     * Enroll new merchants by providing following requested information
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void merchantEnrolmentUsingPOSTTest() {
        MerchantEnrolmentRequest merchantEnrolmentRequest = null;
        String accept = null;

        MerchantEnrolmentResponse response = api.merchantEnrolmentUsingPOST(merchantEnrolmentRequest, accept);

        // TODO: test validations
    }
    
    /**
     * Merchant Search
     *
     * Merchants can be searched by providing following requested information
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void merchantSearchUsingPOSTTest() {
        MerchantSearchRequest merchantSearchRequest = null;
        String accept = null;

        MerchantSearchResponse response = api.merchantSearchUsingPOST(merchantSearchRequest, accept);

        // TODO: test validations
    }
    
}
