/*
 * Visa Account Updater
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.model.BadFormattedErrorMessage;
import org.openapitools.client.model.GenericErrorMessage;
import org.openapitools.client.model.RejectedRequestResponse;
import org.openapitools.client.model.SubscriptionInquiryRequest;
import org.openapitools.client.model.SubscriptionInquiryResponse;
import org.openapitools.client.model.SubscriptionRequest;
import org.openapitools.client.model.SubscriptionResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.springframework.web.client.RestClientException;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for VisaAccountUpdaterSubscriptionApiApi
 */
@Disabled
class VisaAccountUpdaterSubscriptionApiApiTest {

    private final VisaAccountUpdaterSubscriptionApiApi api = new VisaAccountUpdaterSubscriptionApiApi();

    
    /**
     * Subscription API
     *
     * Subscribes the PANs.
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void subscribeUsingPOSTTest() {
        SubscriptionRequest subscriptionRequest = null;
        String accept = null;

        SubscriptionResponse response = api.subscribeUsingPOST(subscriptionRequest, accept);

        // TODO: test validations
    }
    
    /**
     * Inquiry API
     *
     * Retrieve the Accounts subscription information
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void subscriptionInquiryUsingPOSTTest() {
        SubscriptionInquiryRequest subscriptionInquiryRequest = null;
        String accept = null;

        SubscriptionInquiryResponse response = api.subscriptionInquiryUsingPOST(subscriptionInquiryRequest, accept);

        // TODO: test validations
    }
    
}
