/*
 * Visa Account Updater
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.model.BadFormattedErrorMessage1;
import org.openapitools.client.model.GenericErrorMessage1;
import org.openapitools.client.model.RejectedRequestResponse1;
import org.openapitools.client.model.Request;
import org.openapitools.client.model.Response;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.springframework.web.client.RestClientException;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for VisaAccountUpdaterAcquirerApiApi
 */
@Disabled
class VisaAccountUpdaterAcquirerApiApiTest {

    private final VisaAccountUpdaterAcquirerApiApi api = new VisaAccountUpdaterAcquirerApiApi();

    
    /**
     * Acquirer API for PANs Inquiry
     *
     * Retrieve the new PANs information for requested old PANs.
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void inquiryUsingPOSTTest() {
        Request inquiryRequest = null;

        Response response = api.inquiryUsingPOST(inquiryRequest);

        // TODO: test validations
    }
    
}
